'use strict';
const LANGUAGE=document.documentElement.lang==='es'?'es':'ca';
const LOCAL_PHOTOS=LANGUAGE==='es'?PHOTOS.map(p=>({...p,place:TRANSLATIONS_ES.places[p.place]??p.place,comments:p.comments?(TRANSLATIONS_ES.comments[p.order]??p.comments):''})):PHOTOS;
const UI_ES={"fotografies": "fotografías", " fotografies": " fotografías", "Amplia ": "Amplía ", " de ": " de ", "Veure ": "Ver ", "Shimoji · localització de l’illa": "Shimoji · ubicación de la isla", "Réferència aproximada de l’illa. Sense GPS ni punt d’immersió confirmat.": "Referencia aproximada de la isla. Sin GPS ni punto de inmersión confirmado.", " · lloc aproximat": " · lugar aproximado", "No hi ha fotografies amb localització per a aquest dia.": "No hay fotografías con ubicación para este día.", "El mapa no s’ha pogut carregar. Les fotografies continuen disponibles.": "No se ha podido cargar el mapa. Las fotografías siguen disponibles."};
const t=s=>LANGUAGE==='es'?(UI_ES[s]??s):s;
const PAGE_REGION=document.body.dataset.region||'';
const PAGE_PHOTOS=PAGE_REGION?LOCAL_PHOTOS.filter(p=>p.group===PAGE_REGION):LOCAL_PHOTOS;
const ROUTE_POINTS=typeof ROUTE==='undefined'?[]:ROUTE;
const GROUPS=['Honshu','Hokkaido','Okinawa–Yaeyama'];
const COLORS={'Honshu':'#b14f41','Hokkaido':'#456778','Okinawa–Yaeyama':'#447e70'};
const $=id=>document.getElementById(id);
const dateLong=d=>new Intl.DateTimeFormat(LANGUAGE,{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const dateShort=d=>new Intl.DateTimeFormat(LANGUAGE,{day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
let galleryRegion='',galleryDate='',query='',mapRegion='',mapDate='',visible=PAGE_PHOTOS.map((p,i)=>i),current=0,album=[];
const dates=[...new Set(PAGE_PHOTOS.map(p=>p.date))].sort();for(const id of ['gallery-day','map-day'])if($(id))for(const day of dates){const o=node('option',dateLong(day));o.value=day;$(id).append(o);}
const FEATURED=new Set([13,29,52,69,73,88,117,130,149,156,190,209,226,238,246,256,270]);
function photoCard(p,i,featured){const portrait=p.display_aspect<1;const card=node('article',undefined,'photo-card'+(featured?' photo-feature':'')+(portrait?' is-portrait':' is-landscape'));const button=node('button',undefined,'image-button');button.type='button';button.setAttribute('aria-label',t("Amplia ")+(p.place||p.filename));const img=node('img');img.src=p.image;img.srcset=p.image+' '+p.image_width+'w, '+p.image_large+' '+p.image_large_width+'w';img.sizes=featured?'(max-width:700px) 88vw, 85vw':'(max-width:420px) 88vw, (max-width:700px) 45vw, 45vw';img.alt=p.place||p.comments||p.filename;img.loading='lazy';img.decoding='async';img.style.aspectRatio=String(p.display_aspect);button.append(img);button.onclick=()=>openPhoto(i,visible.slice());const text=node('div',undefined,'photo-text');const caption=node('div',undefined,'caption-head');const time=node('time',dateShort(p.date));time.dateTime=p.date;caption.append(node('h4',p.place||''),time);text.append(caption);if(p.comments)text.append(node('p',p.comments));card.append(button,text);return card;}
function layoutRows(items){const result=[];let pending=[],rowNumber=0;function flush(){if(pending.length){result.push({featured:false,items:pending});pending=[];rowNumber++;}}for(let j=0;j<items.length;j++){const item=items[j];if(FEATURED.has(item.p.order)||j===0){flush();result.push({featured:true,items:[item]});continue;}pending.push(item);const target=rowNumber%3===1?3:2;if(pending.length===target)flush();}flush();return result;}
function renderGallery(){const gallery=$('gallery');if(!gallery)return;gallery.replaceChildren();visible=[];for(const g of GROUPS){if(galleryRegion&&g!==galleryRegion)continue;const items=PAGE_PHOTOS.map((p,i)=>({p,i})).filter(({p})=>p.group===g&&(!galleryDate||p.date===galleryDate)&&(!query||[p.place,p.comments,p.filename].join(' ').toLocaleLowerCase(LANGUAGE).includes(query)));if(!items.length)continue;visible.push(...items.map(x=>x.i));const head=node('div',undefined,'region-heading');head.append(node('h3',g));gallery.append(head);const stream=node('div',undefined,'photo-stream');for(const row of layoutRows(items)){if(row.featured){const {p,i}=row.items[0];stream.append(photoCard(p,i,true));}else{const line=node('div',undefined,'photo-row row-'+row.items.length);for(const {p,i} of row.items)line.append(photoCard(p,i,false));stream.append(line);}}gallery.append(stream);}$('empty').hidden=visible.length!==0;document.querySelectorAll('[data-gallery]').forEach(b=>{b.classList.toggle('active',b.dataset.gallery===galleryRegion);b.setAttribute('aria-pressed',String(b.dataset.gallery===galleryRegion));});}
function setGallery(g){galleryRegion=g;renderGallery();}
document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>setGallery(b.dataset.gallery));if($('search'))$('search').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase(LANGUAGE);renderGallery();};if($('gallery-day'))$('gallery-day').onchange=e=>{galleryDate=e.target.value;renderGallery();};if($('reset'))$('reset').onclick=()=>{galleryRegion=galleryDate=query='';$('search').value=$('gallery-day').value='';renderGallery();};
const dialog=$('lightbox');function openPhoto(i,list){current=i;album=list&&list.length?list:visible.slice();if(!album.includes(i))album=[i];updatePhoto();if(!dialog.open)dialog.showModal();document.body.classList.add('modal-open');}
function updatePhoto(){const p=PAGE_PHOTOS[current];$('lb-photo').src=p.image_large||p.image;$('lb-photo').alt=p.place||p.comments||p.filename;$('lb-region').textContent=p.group;$('lb-place').textContent=p.place||'';$('lb-comment').textContent=p.comments||'';$('lb-comment').hidden=!p.comments;$('lb-date').textContent=dateLong(p.date);$('lb-file').textContent=p.filename;$('lb-position').textContent=(album.indexOf(current)+1)+' / '+album.length;$('lb-map').hidden=p.latitude===null;if(p.latitude!==null)$('lb-map').href=`https://www.openstreetmap.org/?mlat=${p.latitude}&mlon=${p.longitude}#map=16/${p.latitude}/${p.longitude}`;}
function movePhoto(step){current=album[(album.indexOf(current)+step+album.length)%album.length];updatePhoto();}document.querySelector('.lb-close').onclick=()=>dialog.close();document.querySelector('.lb-prev').onclick=()=>movePhoto(-1);document.querySelector('.lb-next').onclick=()=>movePhoto(1);dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});document.addEventListener('keydown',e=>{if(!dialog.open)return;if(e.key==='ArrowRight'){e.preventDefault();movePhoto(1);}if(e.key==='ArrowLeft'){e.preventDefault();movePhoto(-1);}});
function routeRegion(p){return p.lat<30?'Okinawa–Yaeyama':p.lat>41.4?'Hokkaido':'Honshu';}
function distance(a,b){const rad=x=>x*Math.PI/180;const v=Math.sin(rad(b.lat-a.lat)/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(rad(b.lon-a.lon)/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
const simplified=[];for(const p of ROUTE_POINTS){const last=simplified.at(-1);if(!last||last.date.slice(0,10)!==p.date.slice(0,10)||distance(last,p)>2)simplified.push(p);}if(ROUTE_POINTS.length&&simplified.at(-1)!==ROUTE_POINTS.at(-1))simplified.push(ROUTE_POINTS.at(-1));
const stops=[];PAGE_PHOTOS.forEach((p,i)=>{if(p.latitude===null){if(p.place.toLocaleLowerCase().includes('shimoji')){let s=stops.find(x=>x.approx&&x.day===p.date);if(!s){s={name:t("Shimoji · localització de l’illa"),group:p.group,day:p.date,lat:24.82,lon:125.15,approx:true,photos:[]};stops.push(s);}s.photos.push(i);}return;}if(p.latitude<24||p.latitude>46||p.longitude<122||p.longitude>146)return;let s=stops.find(x=>!x.approx&&x.group===p.group&&x.day===p.date&&x.name===p.place&&distance({lat:x.lat,lon:x.lon},{lat:p.latitude,lon:p.longitude})<2);if(!s){s={name:p.place||p.group,group:p.group,day:p.date,lat:p.latitude,lon:p.longitude,approx:false,photos:[]};stops.push(s);}s.photos.push(i);});
let map,layers,markers=new Map();function popup(s){const wrap=node('div',undefined,'popup');wrap.append(node('h3',s.name),node('p',dateLong(s.day)));const im=node('img');im.src=PAGE_PHOTOS[s.photos[0]].image;im.alt=s.name;wrap.append(im);if(s.approx)wrap.append(node('p',t("Réferència aproximada de l’illa. Sense GPS ni punt d’immersió confirmat.")));const b=node('button',t("Veure ")+s.photos.length+t(" fotografies"));b.onclick=()=>openPhoto(s.photos[0],s.photos);wrap.append(b);return wrap;}
function renderMap(){const chosen=stops.filter(s=>(!mapRegion||s.group===mapRegion)&&(!mapDate||s.day===mapDate));const list=$('stops');list.replaceChildren();if(map)layers.clearLayers();markers.clear();if(map){for(let i=1;i<simplified.length;i++){const a=simplified[i-1],b=simplified[i],g=routeRegion(b);if(mapRegion&&(g!==mapRegion||routeRegion(a)!==mapRegion))continue;if(mapDate&&(a.date.slice(0,10).replaceAll(':','-')!==mapDate||b.date.slice(0,10).replaceAll(':','-')!==mapDate))continue;const jump=distance(a,b)>100||routeRegion(a)!==g;L.polyline([[a.lat,a.lon],[b.lat,b.lon]],{color:jump?'#8b8e80':COLORS[g],weight:jump?1.5:2,opacity:.65,dashArray:jump?'5 7':'3 5'}).addTo(layers);}}
for(const s of chosen){if(map){const icon=L.divIcon({className:'',html:`<div class="pin${s.approx?' approx':''}" style="background:${COLORS[s.group]}"></div>`,iconSize:s.approx?[23,23]:[17,17],iconAnchor:s.approx?[11,11]:[8,8]});const marker=L.marker([s.lat,s.lon],{icon,title:s.name}).bindPopup(popup(s)).addTo(layers);markers.set(s,marker);}const b=node('button',s.name,'stop');b.append(node('small',dateShort(s.day)+' · '+s.photos.length+' fotos'+(s.approx?t(" · lloc aproximat"):'')));b.onclick=()=>{if(map){map.setView([s.lat,s.lon],s.approx?11:12);markers.get(s).openPopup();}else openPhoto(s.photos[0],s.photos);};list.append(b);}if(!chosen.length)list.append(node('p',t("No hi ha fotografies amb localització per a aquest dia.")));if(map&&chosen.length)map.fitBounds(L.latLngBounds(chosen.map(s=>[s.lat,s.lon])),{padding:[30,30],maxZoom:mapDate?12:mapRegion?8:5});document.querySelectorAll('[data-map]').forEach(b=>{b.classList.toggle('active',b.dataset.map===mapRegion);b.setAttribute('aria-pressed',String(b.dataset.map===mapRegion));});}
function initMap(){if(!$('map'))return;if(typeof L==='undefined'){$('map').append(node('p',t("El mapa no s’ha pogut carregar. Les fotografies continuen disponibles.")));renderMap();return;}map=L.map('map',{scrollWheelZoom:false}).setView([35,135],5);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles &copy; Esri · Esri, HERE, Garmin, Intermap, increment P, GEBCO, USGS, FAO, NPS, NRCAN, GeoBase, IGN, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), swisstopo, MapmyIndia, GIS User Community'}).addTo(map);layers=L.layerGroup().addTo(map);renderMap();}
document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{mapRegion=b.dataset.map;mapDate='';$('map-day').value='';renderMap();});if($('map-day'))$('map-day').onchange=e=>{mapDate=e.target.value;renderMap();};renderGallery();initMap();

const languageSelect=document.getElementById('language-select');if(languageSelect)languageSelect.onchange=e=>{const ca=document.body.dataset.caPage||'index.html';const target=e.target.value==='es'?ca.replace('.html','-es.html'):ca;window.location.href=target+window.location.hash;};

const stickyHeader=document.querySelector('.region-page .site-header');if(stickyHeader){const setHeaderHeight=()=>document.documentElement.style.setProperty('--site-header-height',stickyHeader.getBoundingClientRect().height+'px');setHeaderHeight();if(typeof ResizeObserver!=='undefined')new ResizeObserver(setHeaderHeight).observe(stickyHeader);window.addEventListener('resize',setHeaderHeight);}
